// characters.js

const dbCharacters = [
    // Dragon Ball
    { id: "goku_kid_db", name: { es: "Goku (Niño)", en: "Goku (Kid)", ca: "Son Goku (Nen)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga de Pilaf", en: "Emperor Pilaf Saga", ca: "Saga d'en Pilaf" }, debut_year: 1986, image_url: "https://placehold.co/100x100/orange/white?text=GokuKid" },
    { id: "bulma_db", name: { es: "Bulma (DB)", en: "Bulma (DB)", ca: "Bulma (DB)" }, gender: { es: "Femenino", en: "Female", ca: "Femení" }, hair_color: { es: "Azul", en: "Blue", ca: "Blau" }, race: { es: "Humana", en: "Human", ca: "Humana" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga de Pilaf", en: "Emperor Pilaf Saga", ca: "Saga d'en Pilaf" }, debut_year: 1986, image_url: "https://placehold.co/100x100/orange/white?text=BulmaDB" },
    { id: "roshi_db", name: { es: "Maestro Roshi", en: "Master Roshi", ca: "Follet Tortuga" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Blanco", en: "White", ca: "Blanc" }, race: { es: "Humano", en: "Human", ca: "Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga de Pilaf", en: "Emperor Pilaf Saga", ca: "Saga d'en Pilaf" }, debut_year: 1986, image_url: "https://placehold.co/100x100/orange/white?text=Roshi" },
    { id: "krillin_db", name: { es: "Krilin (DB)", en: "Krillin (DB)", ca: "Krilin (DB)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Humano", en: "Human", ca: "Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga del 21º Torneo Mundial", en: "21st World Martial Arts Tournament Saga", ca: "Saga del 21è Torneig Mundial" }, debut_year: 1986, image_url: "https://placehold.co/100x100/orange/white?text=KrillinDB" },
    { id: "yamcha_db", name: { es: "Yamcha (DB)", en: "Yamcha (DB)", ca: "Yamcha (DB)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Humano", en: "Human", ca: "Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga de Pilaf", en: "Emperor Pilaf Saga", ca: "Saga d'en Pilaf" }, debut_year: 1986, image_url: "https://placehold.co/100x100/orange/white?text=YamchaDB" },
    { id: "tien_db", name: { es: "Ten Shin Han (DB)", en: "Tien (DB)", ca: "Ten Shin Han (DB)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Humano", en: "Human", ca: "Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga del 22º Torneo Mundial", en: "22nd World Martial Arts Tournament Saga", ca: "Saga del 22è Torneig Mundial" }, debut_year: 1987, image_url: "https://placehold.co/100x100/orange/white?text=TienDB" },
    { id: "chiaotzu_db", name: { es: "Chaoz (DB)", en: "Chiaotzu (DB)", ca: "Chaoz (DB)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Humano", en: "Human", ca: "Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga del 22º Torneo Mundial", en: "22nd World Martial Arts Tournament Saga", ca: "Saga del 22è Torneig Mundial" }, debut_year: 1987, image_url: "https://placehold.co/100x100/orange/white?text=ChiaotzuDB" },
    { id: "piccolo_daimao", name: { es: "Piccolo Daimaō", en: "King Piccolo", ca: "Satanàs Cor Petit" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Namekiano", en: "Namekian", ca: "Namekià" }, origin_planet: { es: "Namek", en: "Namek", ca: "Namek" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga de Piccolo Daimaō", en: "King Piccolo Saga", ca: "Saga d'en Satanàs Cor Petit" }, debut_year: 1988, image_url: "https://placehold.co/100x100/orange/white?text=KingPiccolo" },
    { id: "piccolo_jr", name: { es: "Piccolo (Jr.)", en: "Piccolo (Jr.)", ca: "Cor Petit (Jr.)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Namekiano", en: "Namekian", ca: "Namekià" }, origin_planet: { es: "Namek", en: "Namek", ca: "Namek" }, series: { es: "Dragon Ball", en: "Dragon Ball", ca: "Bola de Drac" }, debut_saga: { es: "Saga de Piccolo Jr.", en: "Piccolo Jr. Saga", ca: "Saga d'en Cor Petit Jr." }, debut_year: 1989, image_url: "https://www.giantbomb.com/a/uploads/square_small/46/462814/3223612-piccolo.png" },

    // Dragon Ball Z - Saiyan Saga
    { id: "goku_saiyan_saga", name: { es: "Goku (Saga Saiyan)", en: "Goku (Saiyan Saga)", ca: "Goku (Saga Guerrers de l'Espai)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga Saiyan", en: "Saiyan Saga", ca: "Saga dels Guerrers de l'Espai" }, debut_year: 1989, image_url: "https://placehold.co/100x100/orange/white?text=GokuZ" },
    { id: "gohan_kid_z", name: { es: "Gohan (Niño)", en: "Gohan (Kid)", ca: "Son Gohan (Nen)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Híbrido Saiyan-Humano", en: "Saiyan-Human Hybrid", ca: "Híbrid Saiyà-Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga Saiyan", en: "Saiyan Saga", ca: "Saga dels Guerrers de l'Espai" }, debut_year: 1989, image_url: "https://www.giantbomb.com/a/uploads/square_small/46/462814/3223608-gohan.png" },
    { id: "raditz", name: { es: "Raditz", en: "Raditz", ca: "Raditz" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga Saiyan", en: "Saiyan Saga", ca: "Saga dels Guerrers de l'Espai" }, debut_year: 1989, image_url: "https://www.giantbomb.com/a/uploads/square_small/0/305/2490034-raditz.png" },
    { id: "nappa", name: { es: "Nappa", en: "Nappa", ca: "Nappa" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga Saiyan", en: "Saiyan Saga", ca: "Saga dels Guerrers de l'Espai" }, debut_year: 1989, image_url: "https://www.giantbomb.com/a/uploads/square_small/0/305/2490033-nappa.png" },
    { id: "vegeta_scouter", name: { es: "Vegeta (Scouter)", en: "Vegeta (Scouter)", ca: "Vegeta (Scouter)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga Saiyan", en: "Saiyan Saga", ca: "Saga dels Guerrers de l'Espai" }, debut_year: 1989, image_url: "https://www.giantbomb.com/a/uploads/square_small/46/462814/3223616-vegeta.png" },
    
    // Dragon Ball Z - Namek/Frieza Saga
    { id: "frieza_form1", name: { es: "Freezer (1ª Forma)", en: "Frieza (1st Form)", ca: "Freezer (1a Forma)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Raza de Freezer", en: "Frieza Race", ca: "Raça d'en Freezer" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Namek", en: "Namek Saga", ca: "Saga de Namek" }, debut_year: 1990, image_url: "https://placehold.co/100x100/orange/white?text=Frieza1" },
    { id: "frieza_final", name: { es: "Freezer (Forma Final)", en: "Frieza (Final Form)", ca: "Freezer (Forma Final)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Raza de Freezer", en: "Frieza Race", ca: "Raça d'en Freezer" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Namek", en: "Namek Saga", ca: "Saga de Namek" }, debut_year: 1991, image_url: "https://www.giantbomb.com/a/uploads/square_small/15/157971/2836224-frieza.png" },
    { id: "goku_ssj_namek", name: { es: "Goku (Super Saiyan)", en: "Goku (Super Saiyan)", ca: "Goku (Super Guerrer)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Rubio", en: "Blonde", ca: "Ros" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Namek", en: "Namek Saga", ca: "Saga de Namek" }, debut_year: 1991, image_url: "https://placehold.co/100x100/orange/white?text=GokuSSJ" },
    
    // ... and so on for every character and every form ...
    // This is a massive undertaking, but here's a large chunk to get you started:

    // More Namek Saga
    { id: "zarbon", name: { es: "Zarbon", en: "Zarbon", ca: "Zarbon" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Verde", en: "Green", ca: "Verd" }, race: { es: "Desconocida", en: "Unknown", ca: "Desconeguda" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Namek", en: "Namek Saga", ca: "Saga de Namek" }, debut_year: 1990, image_url: "https://placehold.co/100x100/orange/white?text=Zarbon" },
    { id: "dodoria", name: { es: "Dodoria", en: "Dodoria", ca: "Dodoria" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Desconocida", en: "Unknown", ca: "Desconeguda" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Namek", en: "Namek Saga", ca: "Saga de Namek" }, debut_year: 1990, image_url: "https://placehold.co/100x100/orange/white?text=Dodoria" },
    { id: "ginyu", name: { es: "Capitán Ginyu", en: "Captain Ginyu", ca: "Capità Ginyu" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Desconocida", en: "Unknown", ca: "Desconeguda" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Namek", en: "Namek Saga", ca: "Saga de Namek" }, debut_year: 1990, image_url: "https://placehold.co/100x100/orange/white?text=Ginyu" },
    
    // Android/Cell Saga
    { id: "future_trunks_ssj", name: { es: "Trunks del Futuro (Super Saiyan)", en: "Future Trunks (Super Saiyan)", ca: "Trunks del Futur (Super Guerrer)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Rubio", en: "Blonde", ca: "Ros" }, race: { es: "Híbrido Saiyan-Humano", en: "Saiyan-Human Hybrid", ca: "Híbrid Saiyà-Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de los Androides", en: "Android Saga", ca: "Saga dels Androides" }, debut_year: 1991, image_url: "https://www.giantbomb.com/a/uploads/square_small/46/462814/3223615-trunks.png" },
    { id: "android_17", name: { es: "Androide 17", en: "Android 17", ca: "A-17" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Androide", en: "Android", ca: "Androide" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de los Androides", en: "Android Saga", ca: "Saga dels Androides" }, debut_year: 1991, image_url: "https://www.giantbomb.com/a/uploads/square_small/0/305/2490023-android17.png" },
    { id: "android_18", name: { es: "Androide 18", en: "Android 18", ca: "A-18" }, gender: { es: "Femenino", en: "Female", ca: "Femení" }, hair_color: { es: "Rubio", en: "Blonde", ca: "Ros" }, race: { es: "Androide", en: "Android", ca: "Androide" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de los Androides", en: "Android Saga", ca: "Saga dels Androides" }, debut_year: 1991, image_url: "https://www.giantbomb.com/a/uploads/square_small/15/157971/2836229-android18.png" },
    { id: "cell_perfect", name: { es: "Cell (Perfecto)", en: "Cell (Perfect)", ca: "Cèl·lula (Perfecte)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Bio-Androide", en: "Bio-Android", ca: "Bio-Androide" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Cell", en: "Cell Saga", ca: "Saga d'en Cèl·lula" }, debut_year: 1992, image_url: "https://www.giantbomb.com/a/uploads/square_small/15/157971/2836231-cell.png" },
    { id: "gohan_ssj2", name: { es: "Gohan (Super Saiyan 2)", en: "Gohan (Super Saiyan 2)", ca: "Gohan (Super Guerrer 2)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Rubio", en: "Blonde", ca: "Ros" }, race: { es: "Híbrido Saiyan-Humano", en: "Saiyan-Human Hybrid", ca: "Híbrid Saiyà-Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Cell", en: "Cell Saga", ca: "Saga d'en Cèl·lula" }, debut_year: 1993, image_url: "https://placehold.co/100x100/orange/white?text=GohanSSJ2" },

    // Buu Saga
    { id: "goku_ssj3", name: { es: "Goku (Super Saiyan 3)", en: "Goku (Super Saiyan 3)", ca: "Goku (Super Guerrer 3)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Rubio", en: "Blonde", ca: "Ros" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Majin Buu", en: "Majin Buu Saga", ca: "Saga d'en Buu" }, debut_year: 1994, image_url: "https://placehold.co/100x100/orange/white?text=GokuSSJ3" },
    { id: "majin_vegeta", name: { es: "Majin Vegeta", en: "Majin Vegeta", ca: "Majin Vegeta" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Rubio", en: "Blonde", ca: "Ros" }, race: { es: "Saiyan (Majinizado)", en: "Saiyan (Majin)", ca: "Súper Guerrer (Majinitzat)" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Majin Buu", en: "Majin Buu Saga", ca: "Saga d'en Buu" }, debut_year: 1994, image_url: "https://placehold.co/100x100/orange/white?text=MajinVegeta" },
    { id: "gotenks_ssj3", name: { es: "Gotenks (Super Saiyan 3)", en: "Gotenks (Super Saiyan 3)", ca: "Gotenks (Super Guerrer 3)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Rubio", en: "Blonde", ca: "Ros" }, race: { es: "Saiyan Fusionado", en: "Fused Saiyan", ca: "Súper Guerrer Fusionat" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Majin Buu", en: "Majin Buu Saga", ca: "Saga d'en Buu" }, debut_year: 1994, image_url: "https://placehold.co/100x100/orange/white?text=GotenksSSJ3" },
    { id: "gohan_ultimate", name: { es: "Gohan (Definitivo)", en: "Gohan (Ultimate)", ca: "Gohan (Definitiu)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Híbrido Saiyan-Humano", en: "Saiyan-Human Hybrid", ca: "Híbrid Saiyà-Humà" }, origin_planet: { es: "Tierra", en: "Earth", ca: "Terra" }, series: { es: "Dragon Ball Z", en: "Dragon Ball Z", ca: "Bola de Drac Z" }, debut_saga: { es: "Saga de Majin Buu", en: "Majin Buu Saga", ca: "Saga d'en Buu" }, debut_year: 1994, image_url: "https://placehold.co/100x100/orange/white?text=GohanUlt" },
    
    // Dragon Ball Super

    { id: "beerus_047", name: { es: "Bills", en: "Beerus", ca: "Bills" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Dios de la Destrucción", en: "God of Destruction", ca: "Déu de la Destrucció" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de la Batalla de los Dioses", en: "Battle of Gods Saga", ca: "Saga de la Batalla dels Déus" }, debut_year: 2013, image_url: "https://placehold.co/100x100/orange/white?text=Beerus" },
    { id: "whis_048", name: { es: "Whis", en: "Whis", ca: "Whis" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Blanco", en: "White", ca: "Blanc" }, race: { es: "Ángel", en: "Angel", ca: "Àngel" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de la Batalla de los Dioses", en: "Battle of Gods Saga", ca: "Saga de la Batalla dels Déus" }, debut_year: 2013, image_url: "https://placehold.co/100x100/orange/white?text=Whis" },
    { id: "golden_frieza_118", name: { es: "Golden Freezer", en: "Golden Frieza", ca: "Golden Freezer" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Raza de Freezer", en: "Frieza Race", ca: "Raça d'en Freezer" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de la Resurrección de Freezer", en: "Resurrection 'F' Saga", ca: "Saga de la Resurrecció d'en Freezer" }, debut_year: 2015, image_url: "https://placehold.co/100x100/orange/white?text=GFrieza" },
    { id: "champa_049", name: { es: "Champa", en: "Champa", ca: "Champa" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Dios de la Destrucción", en: "God of Destruction", ca: "Déu de la Destrucció" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga del Universo 6", en: "Universe 6 Saga", ca: "Saga de l'Univers 6" }, debut_year: 2016, image_url: "https://placehold.co/100x100/orange/white?text=Champa" },
    { id: "vados_050", name: { es: "Vados", en: "Vados", ca: "Vados" }, gender: { es: "Femenino", en: "Female", ca: "Femení" }, hair_color: { es: "Blanco", en: "White", ca: "Blanc" }, race: { es: "Ángel", en: "Angel", ca: "Àngel" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga del Universo 6", en: "Universe 6 Saga", ca: "Saga de l'Univers 6" }, debut_year: 2016, image_url: "https://placehold.co/100x100/orange/white?text=Vados" },
    { id: "hit_056", name: { es: "Hit", en: "Hit", ca: "Hit" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Desconocida", en: "Unknown", ca: "Desconeguda" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga del Universo 6", en: "Universe 6 Saga", ca: "Saga de l'Univers 6" }, debut_year: 2016, image_url: "https://placehold.co/100x100/orange/white?text=Hit" },
    { id: "cabba_057", name: { es: "Cabba", en: "Cabba", ca: "Cabba" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Sadala", en: "Sadala", ca: "Sadala" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga del Universo 6", en: "Universe 6 Saga", ca: "Saga de l'Univers 6" }, debut_year: 2016, image_url: "https://placehold.co/100x100/orange/white?text=Cabba" },
    { id: "frost_061", name: { es: "Frost", en: "Frost", ca: "Frost" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Raza de Freezer", en: "Frieza Race", ca: "Raça d'en Freezer" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga del Universo 6", en: "Universe 6 Saga", ca: "Saga de l'Univers 6" }, debut_year: 2016, image_url: "https://placehold.co/100x100/orange/white?text=Frost" },
    { id: "goku_black_063", name: { es: "Goku Black", en: "Goku Black", ca: "Goku Black" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Kaiō (en cuerpo Saiyan)", en: "Kai (in Saiyan body)", ca: "Kaito (en cos de Saiyà)" }, origin_planet: { es: "Planeta Kaiōshin", en: "Sacred World of the Kai", ca: "Planeta dels Kaitoxins" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Trunks del Futuro (Super)", en: "Future Trunks Saga (Super)", ca: "Saga d'en Trunks del Futur (Super)" }, debut_year: 2016, image_url: "https://placehold.co/100x100/orange/white?text=GokuBlack" },
    { id: "zamasu_062", name: { es: "Zamasu", en: "Zamasu", ca: "Zamasu" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Blanco", en: "White", ca: "Blanc" }, race: { es: "Kaiō", en: "Kai", ca: "Kaito" }, origin_planet: { es: "Planeta Kaiōshin", en: "Sacred World of the Kai", ca: "Planeta dels Kaitoxins" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Trunks del Futuro (Super)", en: "Future Trunks Saga (Super)", ca: "Saga d'en Trunks del Futur (Super)" }, debut_year: 2016, image_url: "https://placehold.co/100x100/orange/white?text=Zamasu" },
    { id: "zamasu_fusionado_064", name: { es: "Zamasu Fusionado", en: "Fused Zamasu", ca: "Zamasu Fusionat" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Blanco", en: "White", ca: "Blanc" }, race: { es: "Kaiō Fusionado", en: "Fused Kai", ca: "Kaito Fusionat" }, origin_planet: { es: "Planeta Kaiōshin", en: "Sacred World of the Kai", ca: "Planeta dels Kaitoxins" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Trunks del Futuro (Super)", en: "Future Trunks Saga (Super)", ca: "Saga d'en Trunks del Futur (Super)" }, debut_year: 2016, image_url: "https://placehold.co/100x100/orange/white?text=FZamasu" },
    { id: "jiren_053", name: { es: "Jiren", en: "Jiren", ca: "Jiren" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Desconocida", en: "Unknown", ca: "Desconeguda" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Supervivencia Universal", en: "Universe Survival Saga", ca: "Saga de Supervivència Universal" }, debut_year: 2017, image_url: "https://placehold.co/100x100/orange/white?text=Jiren" },
    { id: "toppo_054", name: { es: "Toppo", en: "Toppo", ca: "Toppo" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Blanco", en: "White", ca: "Blanc" }, race: { es: "Desconocida", en: "Unknown", ca: "Desconeguda" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Supervivencia Universal", en: "Universe Survival Saga", ca: "Saga de Supervivència Universal" }, debut_year: 2017, image_url: "https://placehold.co/100x100/orange/white?text=Toppo" },
    { id: "dyspo_055", name: { es: "Dyspo", en: "Dyspo", ca: "Dyspo" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Ninguno", en: "None", ca: "Cap" }, race: { es: "Desconocida", en: "Unknown", ca: "Desconeguda" }, origin_planet: { es: "Desconocido", en: "Unknown", ca: "Desconegut" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Supervivencia Universal", en: "Universe Survival Saga", ca: "Saga de Supervivència Universal" }, debut_year: 2017, image_url: "https://placehold.co/100x100/orange/white?text=Dyspo" },
    { id: "caulifla_058", name: { es: "Caulifla", en: "Caulifla", ca: "Caulifla" }, gender: { es: "Femenino", en: "Female", ca: "Femení" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Sadala", en: "Sadala", ca: "Sadala" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Supervivencia Universal", en: "Universe Survival Saga", ca: "Saga de Supervivència Universal" }, debut_year: 2017, image_url: "https://placehold.co/100x100/orange/white?text=Caulifla" },
    { id: "kale_059", name: { es: "Kale", en: "Kale", ca: "Kale" }, gender: { es: "Femenino", en: "Female", ca: "Femení" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Sadala", en: "Sadala", ca: "Sadala" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Supervivencia Universal", en: "Universe Survival Saga", ca: "Saga de Supervivència Universal" }, debut_year: 2017, image_url: "https://placehold.co/100x100/orange/white?text=Kale" },
    { id: "kefla_060", name: { es: "Kefla", en: "Kefla", ca: "Kefla" }, gender: { es: "Femenino", en: "Female", ca: "Femení" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan Fusionado", en: "Fused Saiyan", ca: "Súper Guerrer Fusionat" }, origin_planet: { es: "Sadala", en: "Sadala", ca: "Sadala" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Supervivencia Universal", en: "Universe Survival Saga", ca: "Saga de Supervivència Universal" }, debut_year: 2017, image_url: "https://placehold.co/100x100/orange/white?text=Kefla" },
    { id: "broly_super_036", name: { es: "Broly (Super)", en: "Broly (Super)", ca: "Broly (Super)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vampa", en: "Vampa", ca: "Vampa" }, series: { es: "Películas", en: "Movies", ca: "Pel·lícules" }, debut_saga: { es: "Película: Dragon Ball Super: Broly", en: "Movie: Dragon Ball Super: Broly", ca: "Pel·lícula: Dragon Ball Super: Broly" }, debut_year: 2018, image_url: "https://placehold.co/100x100/orange/white?text=BrolyS" },


    { id: "goku_ssg", name: { es: "Goku (Super Saiyan Dios)", en: "Goku (Super Saiyan God)", ca: "Goku (Super Guerrer Déu)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Rojo", en: "Red", ca: "Vermell" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de la Batalla de los Dioses", en: "Battle of Gods Saga", ca: "Saga de la Batalla dels Déus" }, debut_year: 2013, image_url: "https://placehold.co/100x100/orange/white?text=GokuSSG" },
    { id: "goku_ssb", name: { es: "Goku (Super Saiyan Blue)", en: "Goku (Super Saiyan Blue)", ca: "Goku (Super Guerrer Blau)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Azul", en: "Blue", ca: "Blau" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de la Resurrección de Freezer", en: "Resurrection 'F' Saga", ca: "Saga de la Resurrecció d'en Freezer" }, debut_year: 2015, image_url: "https://placehold.co/100x100/orange/white?text=GokuSSB" },
    { id: "vegeta_ssb", name: { es: "Vegeta (Super Saiyan Blue)", en: "Vegeta (Super Saiyan Blue)", ca: "Vegeta (Super Guerrer Blau)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Azul", en: "Blue", ca: "Blau" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de la Resurrección de Freezer", en: "Resurrection 'F' Saga", ca: "Saga de la Resurrecció d'en Freezer" }, debut_year: 2015, image_url: "https://placehold.co/100x100/orange/white?text=VegetaSSB" },
    { id: "goku_ui", name: { es: "Goku (Ultra Instinto)", en: "Goku (Ultra Instinct)", ca: "Goku (Ultra Instint)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Plata", en: "Silver", ca: "Plata" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Supervivencia Universal", en: "Universe Survival Saga", ca: "Saga de Supervivència Universal" }, debut_year: 2018, image_url: "https://placehold.co/100x100/orange/white?text=GokuUI" },
    { id: "vegeta_ssbe", name: { es: "Vegeta (SSB Evolution)", en: "Vegeta (SSB Evolved)", ca: "Vegeta (SSB Evolution)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Azul Oscuro", en: "Dark Blue", ca: "Blau Fosc" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball Super", en: "Dragon Ball Super", ca: "Bola de Drac Super" }, debut_saga: { es: "Saga de Supervivencia Universal", en: "Universe Survival Saga", ca: "Saga de Supervivència Universal" }, debut_year: 2018, image_url: "https://placehold.co/100x100/orange/white?text=VegetaSSBE" },
    
    // Dragon Ball GT
    { id: "goku_gt", name: { es: "Goku (GT)", en: "Goku (GT)", ca: "Goku (GT)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball GT", en: "Dragon Ball GT", ca: "Bola de Drac GT" }, debut_saga: { es: "Saga de las Bolas de Dragón Negras", en: "Black Star Dragon Ball Saga", ca: "Saga de les Boles de Drac d'Estrella Negra" }, debut_year: 1996, image_url: "https://placehold.co/100x100/orange/white?text=GokuGT" },
    { id: "goku_ssj4", name: { es: "Goku (Super Saiyan 4)", en: "Goku (Super Saiyan 4)", ca: "Goku (Super Guerrer 4)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball GT", en: "Dragon Ball GT", ca: "Bola de Drac GT" }, debut_saga: { es: "Saga de Baby", en: "Baby Saga", ca: "Saga d'en Baby" }, debut_year: 1996, image_url: "https://placehold.co/100x100/orange/white?text=GokuSSJ4" },
    { id: "vegeta_ssj4", name: { es: "Vegeta (Super Saiyan 4)", en: "Vegeta (Super Saiyan 4)", ca: "Vegeta (Super Guerrer 4)" }, gender: { es: "Masculino", en: "Male", ca: "Masculí" }, hair_color: { es: "Negro", en: "Black", ca: "Negre" }, race: { es: "Saiyan", en: "Saiyan", ca: "Súper Guerrer" }, origin_planet: { es: "Vegeta", en: "Vegeta", ca: "Vegeta" }, series: { es: "Dragon Ball GT", en: "Dragon Ball GT", ca: "Bola de Drac GT" }, debut_saga: { es: "Saga de los Dragones Oscuros", en: "Shadow Dragon Saga", ca: "Saga dels Dracs Foscos" }, debut_year: 1997, image_url: "https://placehold.co/100x100/orange/white?text=VegetaSSJ4" },]
